version: "3"

services:
  flybondiDB:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - app-vol:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ["--auth"]

  mongo-express:
    depends_on:
      - flybondiDB
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
    ports:
      - 8080:8081
    restart: always

  flybondiBack:
    depends_on:
      - flybondiDB
      - mongo-express
    container_name: "flybondi-server"
    image: ndifabio/flybondi-server:1.0.0
    ports:
      - 8000:8000
    environment:
      MONGO_DB_URI_IOS: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@
      MONGO_DB_NAME: ${MONGO_DB_NAME}:27017
      PORT: ${PORT}
    restart: always

volumes:
  app-vol:
    external: false
